myuser:
  name: 姓名


info:
  app-name: address-server
  description: 地址服务

server:
  port: 8080
spring:
  application:
    name: address-server
  profiles:
    active: dev
  # 配置中心配置
  cloud:
    config:
      retry:
        # 间隔乘数，默认1.1
        multiplier: 1.1
        # 最大间隔时间，默认2000ms
        max-interval: 2000
        # 配置重试次数，默认为6
        max-attempts: 6
        # 初始重试间隔时间，默认1000ms
        initial-interval: 1000
    # 修复github webhook只刷新config server而无法刷新config client的问题
    # https://github.com/spring-cloud/spring-cloud-bus/issues/124
    bus:
      id: ${vcap.application.name:${spring.application.name:application}}:${vcap.application.instance_index:${spring.profiles.active:${local.server.port:${server.port:0}}}}:${vcap.application.instance_id:${random.value}}

management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'