myuser:
  name: wangyunlong-

server:
  port: 8081

spring:
  profiles:
    active: dev
  application:
    name: user-server
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-center
      profile: ${spring.profiles.active}
      label: master
    # 修复github webhook只刷新config server而无法刷新config client的问题
    # https://github.com/spring-cloud/spring-cloud-bus/issues/124
    bus:
      id: ${vcap.application.name:${spring.application.name:application}}:${vcap.application.instance_index:${spring.profiles.active:${local.server.port:${server.port:0}}}}:${vcap.application.instance_id:${random.value}}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka, http://localhost:9001/eureka, http://localhost:9002/eureka

feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 1000
    # 启用okhttp,禁用默认的http,提高qps(okhttp有连接池和超时时间进行调优)
    enabled: false
  okhttp:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  # 已弃用
  #  security:
  #    enabled: false
  endpoint:
    health:
      show-details: always


